# Generated by Django 5.0.7 on 2024-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('day_of_week', models.CharField(max_length=255)),
                ('classroom', models.ManyToManyField(related_name='classrooms', to='classroom.classroom')),
            ],
        ),
    ]
