# Generated by Django 5.0.7 on 2024-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_duration', models.DurationField()),
                ('course_description', models.TextField()),
                ('course_id', models.PositiveSmallIntegerField()),
                ('course_department', models.CharField(max_length=20)),
                ('course_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
    ]
