# Generated by Django 5.0.7 on 2024-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(),
        ),
    ]
