# Generated by Django 5.0.7 on 2024-08-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_duration',
            new_name='course_period',
        ),
    ]
