# Generated by Django 5.0.7 on 2024-07-31 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('class_code', models.PositiveSmallIntegerField()),
                ('class_teacher', models.CharField(max_length=10)),
                ('class_speciality', models.TextField()),
                ('enrollment_date', models.TimeField()),
                ('max_students', models.PositiveSmallIntegerField()),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('start_date', models.PositiveSmallIntegerField()),
                ('end_date', models.PositiveSmallIntegerField()),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='teacher.teacher')),
            ],
        ),
    ]
