# Generated by Django 5.0.7 on 2024-08-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
    ]
