# Generated by Django 5.0.7 on 2024-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_teacher',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
    ]
