# Generated by Django 5.0.7 on 2024-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('bank_account_number', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
    ]
